#Exemple pour windows
# repertoire d'installation de startpilot
startpilot: C:\startpilot
# emplacement des sources du site
jekyll: C:\startpilot\tm
# sous repertoire maitre pour placer les photos
photo_master: infos_asso
# nb pixels de la photo
size: 1024
#chemin complet de l'editeur à utiliser pour afficher le fichier généré
editor: C:\startpilot\tools\Notepad++Portable\Notepad++Portable.exe
#commande à placer avant le nom de l'editeur à lancer
start_cmd: start
# marquage des photos par un copyright
copyright: © trimartolod.free.fr
# site_url site download/upload
site_url: trimartolod.free.fr
# placer les fichiers source modifies dans un .zip sous c:\startpilot\modifs.zip
zip: true
# ftp info
ftp_url: ftpperso.free.fr
ftp_user: trimartolod
# Si nécessaire, infos de proxy
# proxy_addr: proxy.acme.org
# proxy_port: 3128
